name: Java code deployment
on:
  push:
    branches: [ DEV ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted]
    steps:
       - uses: actions/checkout@v2  
       - run: |
           /home/github/apache-maven/bin/mvn clean install
  tomcat-deployment:
    runs-on: [self-hosted]
    needs: build
    steps:
       - name: Run a multi-line script
         run: |
          sh /home/github/deployscripts/tomdeploy.sh
  wildfly-deployment:
    runs-on: [self-hosted]
    needs: build
    steps:
      - name: Hello world action
        env: JBOSS_HOME: ${{ secrets.DEPLOY }}
      - name: Run a multi-line script
        run: |
          sh /home/github/deployscripts/wilddeploy.sh
