name: Java code deployment
on:
  push:
    branches: 
  workflow_dispatch:
env:
    deploy_server: PROD
    war_filename: sample-project-0.0.1-SNAPSHOT.war
jobs:
   test:
      runs-on: self-hosted
      steps:
       - name: tst run
         run: |
             ansible-playbook -i /opt/ansible-playbook/inventory.txt /opt/ansible-playbook/sync.yaml
         env:
            variable: $deploy_server
