name: Java code deployment
on:
  push:
    branches:
            - DEV     
  workflow_dispatch:
env:
    deploy_server: QA
    war_filename: sample-project-0.0.1-SNAPSHOT.war
    git_sha: $GITHUB_SHA
    repo_name: ${{ github.event.repository.name }}
jobs:
   Clone:
      runs-on: [self-hosted]
      steps:
       - name: Clone
         uses: actions/checkout@v3
   Build:
       runs-on: [self-hosted]
       needs: Clone
       steps:
       - name: Build
         run: mvn clean install    
         run: echo $PWD
