name: Java code deployment
on:
  push:
    branches:
            - DEV     
  workflow_dispatch:
env:
    server_group: QA
    war_filename: sample-project-0.0.1-SNAPSHOT.war
    repo_name: ${{ github.event.repository.name }}
jobs:
   Clone:
      runs-on: [self-hosted]
      steps:
       - run: echo "Github SHA for this deployment is: $GITHUB_SHA"
       - name: Clone
         uses: actions/checkout@v3
   Build_LocalCopy:
       runs-on: [self-hosted]
       needs: Clone
       steps:
       - run: mvn clean install
       - run: mkdir -p /opt/artifacts/${{ env.repo_name }}/$GITHUB_SHA
       - run: ls -lht target/$war_filename 
       - run: cp -pr target/$war_filename /opt/artifacts/${{ env.repo_name }}/$GITHUB_SHA/
   Backup_ServerCopy:
       runs-on: [self-hosted]
       needs: Build_LocalCopy
       steps: 
         - run: ansible-playbook -i /opt/ansible-playbook/inventory.txt  /opt/ansible-playbook/wildfly/copy-wildfly-artifact.yml --extra-vars "server_group=${{ env.server_group }} war_name=${{ env.war_filename }} github_sha=$GITHUB_SHA repo_name=${{ env.repo_name }}"
   Deploy:
       runs-on: [self-hosted]
       needs: Backup_ServerCopy
       steps:
          - run: ansible-playbook -i /opt/ansible-playbook/inventory.txt  /opt/ansible-playbook/wildfly/wildfly-deploy.yaml --extra-vars "server_group=QA war_name=${{ env.war_filename }} github_sha=$GITHUB_SHA deployment_dir=/opt/deployment/$(date +%Y)/$(date +%^b)/$(date +%e)"
