name: Java code deployment
on:
  push:
    branches: [ DEV ]
  workflow_dispatch:
env:
    deploy_server: PROD
jobs:
   test:
      runs-on: self-hosted
      steps:
        - run: |
             /usr/bin/ansible-playbook/ansible-playbook /opt/ansible-playbook/sample.yml -i /opt/ansible-playbook/inventory.txt



  
