name: CICD

on:
  push:
    branches: [ DEV ]

  workflow_dispatch:

jobs:
  tomcat:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sh /home/sbhardwa/test.sh
  wildfly:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sh /home/sbhardwa/test1.sh       
