name: Java code deployment
on:
  push:
    branches:
            - DEV     
  workflow_dispatch:
env:
    deploy_server: QA
    war_filename: sample-project-0.0.1-SNAPSHOT.war
    git_sha: $GITHUB_SHA
    repo_name: ${{ github.event.repository.name }}
jobs:
   Clone:
      runs-on: [self-hosted]
      steps:
       - name: Clone
         uses: actions/checkout@v3
   Build_LocalCopy:
       runs-on: [self-hosted]
       needs: Clone
       steps:
       - run: mvn clean install
       - run: sudo mkdir -p /opt/artifacts/$GITHUB_REPOSITORY/$GITHUB_SHA
       - run: cp -pra target/$war_filename /opt/artifacts/$GITHUB_REPOSITORY/$GITHUB_SHA/
