name: test

on:
  push:
    branches: [ DEV ]

  workflow_dispatch:
env:
  GREETING: hello
jobs:
  tomcat:
    runs-on: [self-hosted]

    steps:
       - shell: bash
         env:
            ENV: DEV
            SUB_ENV: ALPHA
            TYPE: API
         run: |
          echo "${{ env.GREETING }} these are $TYPE servers of $ENV $SUB_ENV"
       