name: Java code deployment
on:
  push:
    branches:
            - DEV     
  workflow_dispatch:
env:
    deploy_server: QA
    war_filename: sample-project-0.0.1-SNAPSHOT.war
    git_sha: $GITHUB_SHA
    repo_name: ${{ github.event.repository.name }}
jobs:
   Clone_Build:
      runs-on: [self-hosted]
      steps:
       - name: Build
         run: echo "$env.git_sha"
       - run: echo "$env.repo_name"
