name: Java code deployment
on:
  push:
    branches:
            - DEV     
  workflow_dispatch:
env:
    deploy_server: QA
    war_filename: sample-project-0.0.1-SNAPSHOT.war
    #   git_sha: ${{ GITHUB_SHA }}
jobs:
   Clone_Build:
      runs-on: [self-hosted]
      steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Build
         run: mvn clean install
       - name: Copy
         run: mkdir /opt/chekouts/$GITHUB_REPOSITORY/$GITHUB_SHA/  
       - run: cp -apr  target/sample-project-0.0.1-SNAPSHOT.war /opt/chekouts/$GITHUB_REPOSITORY/$GITHUB_SHA/
