name: Java code deployment

on:
  push:
    branches: [ PROD ]

  workflow_dispatch:

jobs:
  tomcat:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo $super_secret > /tmp/test1

      - name: Run a multi-line script
        run: |
          sh /home/sbhardwa/test.sh
        env: 
           super_secret: ${{ secrets.DEPLOY }}
  wildfly:
    runs-on: [self-hosted]
    needs: tomcat
    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          sh /home/sbhardwa/test1.sh       
